# Generated by Django 4.1.5 on 2025-08-24 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='igtf_percentage',
            field=models.DecimalField(decimal_places=2, default=3.0, max_digits=5),
        ),
    ]
