# Generated by Django 4.1.5 on 2025-08-23 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_price_category_prefix_product_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='applies_iva',
            field=models.BooleanField(default=False),
        ),
    ]
