# Generated by Django 4.1.5 on 2025-08-24 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('products', '0007_alter_product_category_alter_product_supplier_and_more'),
        ('customers', '0003_alter_customer_address_alter_customer_email_and_more'),
        ('sales', '0005_sale_status_sale_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='exchange_rate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.exchangerate'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product'),
        ),
        migrations.AlterModelTable(
            name='sale',
            table=None,
        ),
        migrations.AlterModelTable(
            name='saledetail',
            table=None,
        ),
    ]
