# Generated by Django 4.1.5 on 2025-08-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_sale_customer_alter_sale_exchange_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='credit_paid',
            field=models.BooleanField(default=False),
        ),
    ]
