# Generated by Django 4.1.5 on 2025-09-08 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_remove_sale_amount_payed_remove_sale_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('pending_credit', 'Pending Credit')], default='completed', max_length=20),
        ),
    ]
