# Generated by Django 4.1.5 on 2025-09-11 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_alter_sale_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='credit_paid',
        ),
        migrations.AddField(
            model_name='sale',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('pending_credit', 'Pending Credit'), ('partially_paid', 'Partially Paid')], default='completed', max_length=20),
        ),
    ]
