# Generated by Django 4.1.5 on 2025-09-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_remove_sale_credit_paid_sale_amount_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditpayment',
            name='igtf_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
