# Generated by Django 4.1.5 on 2025-08-23 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='outstanding_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='tax_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
